### PR TITLE
Steps to version 1.2.0.0

### PR DESCRIPTION
**Pull request by ScriptSlayer0**

### CODE REVIEW

**Comment by HarbingerOfFire** [comment]
Do you think we could fix that SonarCloud check on commit 1b52ff7?

**Comment by ScriptSlayer0** [comment]
I think it's important to fix it slowly and then merge it.
As for the duplication of code, it's a small chunk to fix, it might be easy to fix.

**Comment by HarbingerOfFire** [comment]
Looking good! I'll update the version numbers and merge

**Comment by ScriptSlayer0** [comment]
Okey, let's go!

**Comment by HarbingerOfFire** [comment]
Duplication back. I can fix it...

**Comment by ScriptSlayer0** [comment]
There is a problem with user interaction

**Comment by HarbingerOfFire** [comment]
Fixed!

**Pull request merged**
