### PR TITLE
Security update & code sorting

### PR DESCRIPTION
**Pull request by ScriptSlayer0**
I have been working on it with version `1.1.0.1` or in the pre-release (On dubs now):

- [X] In the encryption module, it already has key derivation. 

- [X]  Multiple modifications, for better understanding and better maintenance of the code.

### CODE REVIEW

**Comment by ScriptSlayer0** [comment]
This update I have been working about the commit 0104e225c32234106337039ee6d9412d8a5f8ccb

**Comment by ScriptSlayer0** [comment]
I've forgotten a small detail, the issue of generating keys is solved, because before always created a new pair of keys and on the module encrypt.py it is solved

**Comment by HarbingerOfFire** [comment]
It seems to pass all the tests I can think of. The only suggestion I have is to add an `end=''` parameter to the print statement for info about key generation, that way the confirmation that the keys are saved is on the same line as the one that says they are generating, improving screen space consumption.

**Comment by HarbingerOfFire** [comment]
I went ahead and made those edits and incremented the version number.

**Review by HarbingerOfFire — COMMENTED** [review]
looks good 👍

**Comment by ScriptSlayer0** [comment]
👌 Thanks @HarbingerOfFire

**Pull request merged**
